### ISSUE TITLE
Cannot get a value from /public/dapperUtilityCoinBalance of account 

### ISSUE THREAD

**Issue by UCT10** [dapperlabs/nba-smart-contracts#102]
The initial issue is here: https://github.com/onflow/cadence/issues/667

I'm trying to figure out how to get my Dapper Balance from blockchain. Unfortunately, none of the instructions work. Can I actually get Dapper balance from my account with blockchain? If you want to check, my TS Flow account is 0x74040f9a566af82b and my current balance is 200 USD. Thanks.

... Some attempts...

Hm, somehow I managed to get a response with this one:
```
import FungibleToken from 0xf233dcee88fe0abe
import DapperUtilityCoin from 0xead892083b3e2c6c

pub fun main(): &DapperUtilityCoin.Vault{FungibleToken.Receiver}? {
    let acct = getAccount(0x74040f9a566af82b)
    let vaultRef = acct.getCapability(/public/dapperUtilityCoinReceiver).borrow<&DapperUtilityCoin.Vault{FungibleToken.Receiver}>()

    return vaultRef
}
```
The response is:
```
{"type":"Optional","value":{"type":"Resource","value":{"id":"A.e544175ee0461c4b.TokenForwarding.Forwarder","fields":[{"name":"uuid","value":{"type":"UInt64","value":"3863274"}},{"name":"recipient","value":{"type":"Capability","value":{"path":{"type":"Path","value":{"domain":"public","identifier":"dapperUtilityCoinReceiver"}},"address":"0xead892083b3e2c6c","borrowType":""}}}]}}}
```
There's only uuid of Forwarder, but there's no certain amount. Can I get amount of DUC from there? 
Or maybe there's a different approach, what's a transaction of deposit funds to Dapper from crypto or debit card? I didn't see anything of this type in blockchain. Can you please provide the txid of any?
...
I'm a total newbie to cadence and flow blockchain, so forgive me. [It helped, but only particularly](https://github.com/onflow/flow-ft/blob/1bef2c5862cb3e34753967389036efd53ac6776d/transactions/scripts/get_balance.cdc)
But the result is frustrating. I cannot get any value except the Main Vault.

```
import FungibleToken from 0xf233dcee88fe0abe
import DapperUtilityCoin from 0xead892083b3e2c6c

pub fun main(): &DapperUtilityCoin.Vault{FungibleToken.Balance}? {
    let acct = getAccount(0xead892083b3e2c6c)
    let vaultRef = acct.getCapability(/public/dapperUtilityCoinBalance).borrow<&DapperUtilityCoin.Vault{FungibleToken.Balance}>()

    return vaultRef
}
```
The response is:
```
{"type":"Optional","value":{"type":"Resource","value":{"id":"A.ead892083b3e2c6c.DapperUtilityCoin.Vault","fields":[{"name":"uuid","value":{"type":"UInt64","value":"2"}},{"name":"balance","value":{"type":"UFix64","value":"999999999.00000000"}}]}}}
```
It seems that DUC was just minted at the beginning of the whole story, and the community might not be able to control the legitimate of its emission. And this is without a mention that Dapper users don't control either private keys, their money (DUC), only NFT collections and only through nbatopshot.com UI. If I'm wrong at anything, please, correct me.

Still, there's a question. Is there any way I can see deposits and withdrawals of TS user's money? Is there any way I can audit whether DUCs are backed by real dollars or not? If there's no such way, then why?
It's stated that products on Flow blockchain are transparent, so this feature is crucially required if it's not implemented yet.

**Comment by UCT10** [comment]
@psiemens @joshuahannan @10thfloor

**Comment by joshuahannan** [comment]
@UCT10 You are correct that there are no fungible tokens stored in a dapper user's account at this point. Dapper wallets use the [Token Forwarding contract](https://github.com/onflow/flow-ft/blob/master/contracts/utilityContracts/TokenForwarding.cdc), which replaces the DUC receiver in each account and forwards it back to the main dapper account. The history of DUC marketplace transactions can be constructed by querying Token Fowarding events for the address in question, but no actual tokens are stored in a Dapper user's account except for the Top Shot NFTs. 

Dapper credits are backed by real dollars because Dapper has agreements with regulated financial institutions to keep users funds safe. There is nothing for you to worry about. Soon, you'll be able to transfer your Top Shot NFTs to external accounts if you would like to have full control of your assets.

**Comment by turbolent** [comment]
@UCT10 As I wrote in the other issue, this is the repository of the Cadence programming language, and the Dapper smart contracts are from the Dapper Wallet, a product of Dapper Labs.  We can't help with questions on how to use specific smart contracts here.

**Comment by turbolent** [comment]
Sorry @UCT10, I got confused for a moment and thought this was another issue in the Cadence repo. Thank you for asking here 👍

**Comment by UCT10** [comment]
(What's going on there with TopShot, guys? Want to catch some transactions but there's none)
Ok, I've tried to search for events of Token forwarding. It approximately has the structure "amount - receiver", but there's no sender :( What's the best way to get the sender? I'm using flow-go-sdk. Approximate code is as follows:
```
func main() {
// some code

	blockEvents, err := flowClient.GetEventsForHeightRange(context.Background(), client.EventRangeQuery{
		Type:        "A.e544175ee0461c4b.TokenForwarding.ForwardedDeposit",
		StartHeight: 12534839 - 500,
		EndHeight:   12534839,
	})

	for _, blockEvent := range blockEvents {
		for _, purchaseEvent := range blockEvent.Events {
                    fmt.Println(purchaseEvent.Value)
		}
	}
}

```
And the response is: 
```
{0xc0005e2550 [38000000000 {cd99eb940d231b1c}]}
{0xc0005e25a0 [865000000 {faf0cc52c6e3acaf}]}
{0xc0005e25f0 [16435000000 {d5a61dbf90a105ae}]}
{0xc0005e2640 [75000000 {faf0cc52c6e3acaf}]}
{0xc0005e2690 [1425000000 {bc2a6c03451ecc6d}]}
{0xc0005e26e0 [90000000 {faf0cc52c6e3acaf}]}
{0xc0005e2730 [1710000000 {dc11a1698b9041cd}]}
```
The second question, is Dapper Balance deposits are on-chain or off-chain? It seems to be off-chain with a further on-chain update. Or there are no on-chain Dapper deposits? If there's, what's a stereotypical transaction for this? Thanks!

**Comment by joshuahannan** [comment]
DUC transfers always have the same sender. For every purchase, the DUC admin mints the tokens required for the purchase, deposits them to the sellers sale, then the tokens are forwarded back to the DUC admin. Dapper Credit balances are recorded off-chain, but they listen to the on-chain events to get the numbers to update them.

**Comment by UCT10** [comment]
Ah, right. It's always the same sender. Thanks! I'll search for ways to calculate deposits with another approach then.

**Comment by bluesign** [comment]
"Dapper Credit balances are recorded off-chain, but they listen to the on-chain events to get the numbers to update them."

@joshuahannan  this sounds like an invitation to trouble.

**Comment by UCT10** [comment]
> "Dapper Credit balances are recorded off-chain, but they listen to the on-chain events to get the numbers to update them."
> 
> @joshuahannan this sounds like an invitation to trouble.

And it is the common source of issues to be honest. There were 3-4 maintenances because of dapper balance issues. Also the db can possibly be hacked in a sophisticated way. In almost all cases it's better to store this data on chain. I think we can reopen this issue.

**Comment by joshuahannan** [comment]
@bluesign @UCT10 this is not an issue with the NBA Top Shot smart contracts. It is an issue with the Dapper Wallet. There are complicated legal and regulatory reasons that Dapper chose to do it this way, but this is not the place to discuss them. Please reach out to `support@meetdapper.com` if you have concerns.
