### ISSUE TITLE
Create Metadata Upgrade that conforms with the proposed NFT metadata standard

### ISSUE THREAD

**Issue by joshuahannan** [dapperlabs/nba-smart-contracts#132]
### Issue To Be Solved
The community is reaching final steps for the Flow NFT metadata standard, and for the last steps of it, it would be helpful to have some examples of the standard in practice. Top Shot is a great place to show it.

NFT Standard Repo Instructions Here (with example implementation): https://github.com/onflow/flow-nft/pull/52
NFT Standard View Proposals (contribute to this discussion and use the relevant views from this): https://github.com/onflow/flow-nft/pull/55

Example implementation for a different project is here: https://github.com/findonflow/find/blob/main/contracts/Art.cdc

### Suggest A Solution

* Get familiar with the metadata proposal
* Define a view in the top shot smart contract for all the [text-based metadata](https://github.com/dapperlabs/nba-smart-contracts/blob/master/lib/go/templates/data/play_metadata.go#L6) that the Top Shot `NFT` already contains in the `metadata` dictionary.
* Add implementations of the `getView` and `resolveView` methods to the `TopShot.NFT` resource.
    * Should have a `resolveView` for `MetadataViews.Display` and for the newly defined view
* Add these methods to the collection resource as well to get it for a specific NFT ID.
* Write tests to ensure that these work properly
* Add documentation for these metadata views and how to access them

**Comment by HouseOfHufflepuff** [comment]
PR merged to master. Closing ticket.
