### ISSUE TITLE
Add specific thumbnail for NFTs instead of a placeholder image

### ISSUE THREAD

**Issue by LanfordCai** [dapperlabs/nba-smart-contracts#156]
Currently, the MetadataViews.Display thumbnail of the Moments are a hardcoded url: 
https://ipfs.dapperlabs.com/ipfs/Qmbdj1agtbzpPWZ81wCGaDiMKRFaRN3TU6cfztVCu6nh4o, but it should be different between Moments, which limit the display of Moments in other Flow ecosystem projects.

Is there any way to get the thumbnail like collective.xyz?
<img width="296" alt="image" src="https://user-images.githubusercontent.com/10380321/186145297-48776a19-b1ba-46fd-b505-0eb300e80a5f.png">

Or do you have any plan to fix this?

**Comment by jrkhan** [comment]
Hello! In the near future we are looking to provide a number of media URLs along with each NFT. 
Unfortunately some of the parameters needed to create the media URIs are currently not on chain.
We have in flight an image gateway that will provide somewhat easier to consume URLs and require only on chain data. Once that is in, we will plan to make use of those in our Medias metadata view which you can retrieve via Cadence query.  
Please see:
[https://www.flow-nft-catalog.com/](https://www.flow-nft-catalog.com/) for a description of the metadata views we plan to implement) 


While I can't give you a definite timeline on this, I can refer you to an WIP progress branch for the feature (note that the pattern for building URIs will change from the helper currently in the branch):
https://github.com/dapperlabs/nba-smart-contracts/tree/feature/core-nft-views

Let me know if you have any further questions or concerns.

**Comment by LanfordCai** [comment]
@jrkhan Hi! Thank you for your reply! I still have two questions:
1. Could you make `thumbnail` available ahead of other media types? It would be nice for the other projects to display the Moments
2. Or s there any way for other projects to get the thumbnail now like collective.xyz?

**Comment by jrkhan** [comment]
Hello!
1. Unfortunately, there isn't really a great way to make just the thumbnail available ahead of the other types (once we can support one type, we'll be able to support all of them, if that makes sense)
2. There is a way to get the thumbnail now, but you would need to know the 'play guid '(not currently on chain), along with the 'set visual id' (also not on chain) and the 'set name' in order to build the image url. You might be able to get at these through the nba topshot graphql api though. Do you have a timeline for when you're looking to have the thumbnail?

**Comment by LanfordCai** [comment]
@jrkhan Hi! Thank you for your response! 

I created an application named drizzle(https://drizzle33.app) weeks ago. It's a platform for anyone to create airdrop and NFT raffle, and I'm going to add NBATopshot to it so that the community can create NFT raffle with Moments as rewards. But I found the thumbnail is not displayed as expected, so I came here and asked for details. It would be nice to access to the thumbnails now so that I can finish my integration asap, but it's ok if it is not open to public now, I'll wait for the implementation of Metadaviews. Thank you!

**Comment by jrkhan** [comment]
Hello @LanfordCai - wanted to let you know this should be resolved by:
https://github.com/dapperlabs/nba-smart-contracts/pull/161
Which should now be available on mainnet.
You should also find a new medias metadata view that should provide additional images for each moment.

**Comment by LanfordCai** [comment]
It awesome! Thank you @jrkhan

**Comment by LanfordCai** [comment]
Hello @jrkhan , I want to know is it allowed to display this thumbnail exposed by TopShot contracts in my Flow projects? Or it will cause some IP issues?
